import { pgTable, serial, text, integer, timestamp, jsonb, varchar } from "drizzle-orm/pg-core";

export type ContactPhone = { number: string; whatsapp: boolean };

export const siteSettingsTable = pgTable("site_settings", {
  id: serial("id").primaryKey(),
  siteTitleEn: text("site_title_en").notNull().default(""),
  siteTitleAr: text("site_title_ar").notNull().default(""),
  conferenceYear: integer("conference_year").notNull().default(2026),
  conferenceNumber: integer("conference_number").notNull().default(2),
  conferenceOrdinalEn: text("conference_ordinal_en").notNull().default(""),
  conferenceOrdinalAr: text("conference_ordinal_ar").notNull().default(""),
  conferenceDatesEn: text("conference_dates_en").notNull().default(""),
  conferenceDatesAr: text("conference_dates_ar").notNull().default(""),
  venueNameEn: text("venue_name_en").notNull().default(""),
  venueNameAr: text("venue_name_ar").notNull().default(""),
  venueDescEn: text("venue_desc_en").notNull().default(""),
  venueDescAr: text("venue_desc_ar").notNull().default(""),
  contactPhone: text("contact_phone").notNull().default(""),
  contactWhatsapp: text("contact_whatsapp").notNull().default(""),
  contactPhones: jsonb("contact_phones").$type<ContactPhone[]>().notNull().default([]),
  contactEmails: jsonb("contact_emails").$type<string[]>().notNull().default([]),
  heroMode: varchar("hero_mode", { length: 16 }).notNull().default("images"),
  heroVideoUrl: text("hero_video_url"),
  seoTitleEn: text("seo_title_en").notNull().default(""),
  seoTitleAr: text("seo_title_ar").notNull().default(""),
  seoDescEn: text("seo_desc_en").notNull().default(""),
  seoDescAr: text("seo_desc_ar").notNull().default(""),
  footerNoteEn: text("footer_note_en").notNull().default(""),
  footerNoteAr: text("footer_note_ar").notNull().default(""),
  logoUrl: text("logo_url"),
  faviconUrl: text("favicon_url"),
  socialImageUrl: text("social_image_url"),
  venueImageUrl: text("venue_image_url"),
  aboutImageUrl: text("about_image_url"),
  quoteImageUrl: text("quote_image_url"),
  fontEn: text("font_en").notNull().default("Fraunces"),
  fontAr: text("font_ar").notNull().default("Cairo"),
  fontEnUrl: text("font_en_url"),
  fontArUrl: text("font_ar_url"),
  statEditions: text("stat_editions").notNull().default("02"),
  statEditionsLabelEn: text("stat_editions_label_en").notNull().default(""),
  statEditionsLabelAr: text("stat_editions_label_ar").notNull().default(""),
  statDelegates: text("stat_delegates").notNull().default("500+"),
  statDelegatesLabelEn: text("stat_delegates_label_en").notNull().default(""),
  statDelegatesLabelAr: text("stat_delegates_label_ar").notNull().default(""),
  statFaculty: text("stat_faculty").notNull().default("35"),
  statFacultyLabelEn: text("stat_faculty_label_en").notNull().default(""),
  statFacultyLabelAr: text("stat_faculty_label_ar").notNull().default(""),
  statCmeHours: text("stat_cme_hours").notNull().default("12"),
  statCmeHoursLabelEn: text("stat_cme_hours_label_en").notNull().default(""),
  statCmeHoursLabelAr: text("stat_cme_hours_label_ar").notNull().default(""),
  statCountries: text("stat_countries").notNull().default("4"),
  statCountriesLabelEn: text("stat_countries_label_en").notNull().default(""),
  statCountriesLabelAr: text("stat_countries_label_ar").notNull().default(""),
  heroCtaFormSlug: text("hero_cta_form_slug"),
  heroCtaLabelEn: text("hero_cta_label_en").notNull().default(""),
  heroCtaLabelAr: text("hero_cta_label_ar").notNull().default(""),
  heroSecondaryCtaMode: varchar("hero_secondary_cta_mode", { length: 32 }).notNull().default("contact"),
  heroSecondaryCtaLabelEn: text("hero_secondary_cta_label_en").notNull().default(""),
  heroSecondaryCtaLabelAr: text("hero_secondary_cta_label_ar").notNull().default(""),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

export type SiteSettings = typeof siteSettingsTable.$inferSelect;
